apiVersion: v1
kind: Secret
metadata:
  name: sample-bucket-provider-env-configuration
  namespace: minio-tenant-sample-bucket-provider
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="admin"
    export MINIO_ROOT_PASSWORD="password"
