apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: sample-bucket-provider
  namespace: minio-tenant-sample-bucket-provider
spec:
  image: quay.io/minio/minio:RELEASE.2023-05-27T05-56-19Z
  imagePullPolicy: IfNotPresent
  configuration:
    name: sample-bucket-provider-env-configuration
  pools:
    - servers: 3
      name: pool-0
      volumesPerServer: 3
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: rook-ceph-block
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containerSecurityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
  mountPath: /export
  subPath: /data
  requestAutoCert: true
  features:
    bucketDNS: false
  podManagementPolicy: Parallel
  prometheusOperator: false
  logging:
    anonymous: true
    json: true
    quiet: true
