apiVersion: apps/v1
kind: Deployment
metadata:
  name: "console"
  namespace: minio-operator
  labels:
    helm.sh/chart: operator-5.0.5
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/version: "v5.0.5"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: operator
      app.kubernetes.io/instance: minio-operator-console
  template:
    metadata:
      labels:
        app.kubernetes.io/name: operator
        app.kubernetes.io/instance: minio-operator-console
    spec:
      serviceAccountName: console-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: operator
          image: "quay.io/minio/operator:v5.0.5"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 9443
              name: https
          args:
            - ui
            - --certs-dir=/tmp/certs
          resources: {}
          volumeMounts:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "minio-operator"
  namespace: minio-operator
  labels:
    helm.sh/chart: operator-5.0.5
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/version: "v5.0.5"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: operator
      app.kubernetes.io/instance: minio-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: operator
        app.kubernetes.io/instance: minio-operator
    spec:
      serviceAccountName: minio-operator
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - minio-operator
              topologyKey: kubernetes.io/hostname
      containers:
        - name: operator
          image: "quay.io/minio/operator:v5.0.5"
          imagePullPolicy: IfNotPresent
          args:
            - controller
          resources:
            requests:
              cpu: 200m
              ephemeral-storage: 500Mi
              memory: 256Mi
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
