apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-sa
  namespace: minio-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-operator
  namespace: minio-operator
  labels:
    helm.sh/chart: operator-5.0.5
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/version: "v5.0.5"
    app.kubernetes.io/managed-by: Helm
