apiVersion: v1
kind: Service
metadata:
  name: "console"
  namespace: minio-operator
  labels:
    helm.sh/chart: operator-5.0.5
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/version: "v5.0.5"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: http
      port: 9090
    - name: https
      port: 9443
  selector:
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: minio-operator-console
---
apiVersion: v1
kind: Service
metadata:
  name: "operator"
  namespace: minio-operator
  labels:
    helm.sh/chart: operator-5.0.5
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/version: "v5.0.5"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 4221
      name: http
  selector:
    operator: leader
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: minio-operator
---
apiVersion: v1
kind: Service
metadata:
  name: "sts"
  namespace: minio-operator
  labels:
    helm.sh/chart: operator-5.0.5
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/version: "v5.0.5"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 4223
      name: https
  selector:
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: minio-operator
